title: My title 
theme: minima
author: Me, myself and I
email: mytest@test.com
description: > # this means to ignore newlines until "baseurl:"
  I need to change descprition

# social links
twitter_username: iamnotusingit # DO NOT include the @ character, or else the build will fail!
github_username:  piotrgorgsol # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
